config/routes.rb
RottenBananas::Application.routes.draw do
 
  devise_for :users
  resources :reviews

  resources :films

  root 'films#homepage'

  get 'films/:film_id/reviews/new' => 'reviews#new', as: :new_film_review

end

app/models/film.rb
class Film < ActiveRecord::Base
  has_many :reviews
  belongs_to :user

  validates :title, presence: true 
  validates :director, presence: true
  validates :studio, presence: true

  def self.search(search)
    if search
      find(:all, :conditions =>['title LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/models/review.rb
# class ReviewAuthor < ActiveRecord::Base
#   has_many :films
#   has_many :reviews, through: :films
# end



class Review < ActiveRecord::Base
  belongs_to :film
  belongs_to :user

  validates :film_id, presence: true 
  validates :comment, presence: true
  validates :author, presence: true
  validates :number_of_stars, inclusion: { in: 1..10 }

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :films
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
before_action :authenticate_user!, except:[:index, :show]


  def new
    @film = Film.new
  end

  def create
    @film = Film.new(film_params)
    if @film.valid?
      @film.save
      redirect_to @film
    else
      render :new
    end
  end

  def show
    @film = Film.find(params[:id])
  end

  def index
    @films = Film.search(params[:search])
    # @films = Film.all
  end

  def update
    @film = Film.find(params[:id])
    if @film.update(film_params)
      redirect_to @film
    else
      render 'edit'
    end
  end

  def edit
    @film = Film.find(params[:id])
  end

  def destroy
    @film = Film.find(params[:id])
    @film.destroy

    redirect_to films_path, notice: "That film has been deleted"
  end

  private

  def film_params
    params.require(:film).permit(:title, :director, :studio)
  end
 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_filter :authenticate_user!, except:[:index, :show]
  
  def new
    @review = Review.new
    @review.film = Film.find(params[:film_id])
  end

  def create
    @review = Review.new(review_params)
    if @review.valid?
      @review.save
      redirect_to @review
    else
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def index
    @reviews = Review.all
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to @review
    else
      render 'edit'
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to @review.film, notice: "That review has been deleted."
  end

  private

  def review_params
    params.require(:review).permit(:film_id, :comment, :number_of_stars, :author)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/films/edit.html.erb
<h2>Editing film</h2>
 
<%= form_for :film, url: film_path(@film), method: :patch do |f| %>
  <% if @film.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@film.errors.count, "error") %> prohibited
      this film from being saved:</h2>
    <ul>
    <% @film.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  
  <%= f.label :studio %><br>
  <%= f.text_field :studio %><br>
  
  <%= f.label :director %><br>
  <%= f.text_field :director %><br><br>




  <br><br>

  
  <%= f.submit "Update" %>
<% end %></p>
 
<%= link_to 'Back', films_path %>

app/views/films/index.html.erb
  <h2>Films (click for reviews)</h2>

  
<% @films.each do |film| %><br>
<%= link_to film.title, film_path(film) %><br>
<%= film.director %><br>
<%= film.studio %><br>
<% end %>
<div>
<h1><%= link_to 'Add a film', new_film_path %></h1>
</div>

app/views/films/new.html.erb
<%= form_for @film, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
    
  <% if @film.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@film.errors.count, "error") %> prohibited this film from being saved:</h2>
 
    <ul>
    <% @film.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  
  <%= f.label :studio %><br>
  <%= f.text_field :studio %><br>
  
  <%= f.label :director %><br>
  <%= f.text_field :director %><br><br>




  <br><br>

  
  <%= f.submit "create" %>
<% end %>

<%#= link_to 'Films', films_path %>

app/views/films/show.html.erb
<h2>Film: <%= @film.title %></h2>


<p>Director: <%= @film.director %></p>
<p>Studio: <%= @film.studio %></p>

<!--  -->
<!-- add reviews in here -->

<% @film.reviews.each  do |review| %>
  <div class="review_box">
    <p>
      <h3><%= review.author %></h3>
    </p>
    <p>
      <%= review.number_of_stars %> out of 10
    </p>
    <p><strong>Review:</strong>
      <em><%= review.comment %></em>
    </p>
    <%= link_to 'See Review', review_path(review) %>
  </div>
<% end %>


<%#= link_to 'List of films', films_path %> 

<%= link_to 'Add a review for this film', new_film_review_path(film_id: @film.id) %>

<%= link_to 'Edit film', edit_film_path(@film) %>

<%= button_to 'Delete film', film_path(@film),
                          method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenBananas</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "jquery.js", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header">
    <h1>ROTTEN
          <%= image_tag('banana.png', :alt => 'banana logo', :class => 'banana') %>
          BANANAS</h1><div id='secrets'></div>
      <ul>
        <li><%= link_to 'Films', films_path %></li>
        <li><%= link_to 'Reviews', reviews_path %></li>
        <% if user_signed_in? %>
        <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
        </li>
        <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>  
        </li>
      </ul>    
      <% end %>
      <div>
        <%=form_tag films_path, :method => 'get' do %>
        <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name => nil %>
        </p>
        <% end %>
      </div>
      <%= flash[:notice] %>
    </div>
    <div>
      <%= flash[:warning] %>
    </div>
    <div>
      <%= flash[:alert] %>
    </div>
    <div class="THEBOX">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/edit.html.erb
<h2>Editing review</h2>
 
<%= form_for @review, url: review_path(@review), method: :patch do |f| %>
  <% if @review.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error") %> prohibited
      this review from being saved:</h2>
    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
  <%= f.label :film_id %><br>
  <%= f.collection_select(:film_id, Film.all, :id, :title) %>
<br>
  
  <%= f.label :number_of_stars %><br>
  <% (1..10).each do |star| %>
    <%= f.label star %> 
    <%= f.radio_button(:number_of_stars, star) %>
  <% end %>



  <br><br>
  <%= f.label :comment %><br>
  <%= f.text_area :comment, size: "60x12" %><br>
  <%= f.label :author %><br>
  <%= f.text_field :author %><br>
  
  <%= f.submit "create" %>
<% end %></p>
 
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h2>Reviews thus far</h2>
<% @reviews.each do |review| %>
<div>
  <%= review.film.title %>: <%= review.film.director %>
  <p><%= review.comment %></p>
</div>
<% end %>

<%#= link_to 'List of films', films_path %> 

app/views/reviews/new.html.erb
<%= form_for @review, html: {class: "nifty_form"} do |f| %>
    
  <% if @review.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>
 
    <ul>
    <% @review.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  

  <%= f.label :film_id %><br>
  <%= f.collection_select(:film_id, Film.all, :id, :title) %><br>
  
  <%= f.label :number_of_stars %><br>
  <% (1..10).each do |star| %>
    <%= f.label star %> 
    <%= f.radio_button(:number_of_stars, star) %>
  <% end %>



  <br><br>
  <%= f.label :comment %><br>
  <%= f.text_area :comment, size: "60x12" %><br>
  <%= f.label :author %><br>
  <%= f.text_field :author %><br>
  
  <%= f.submit "create" %>
<% end %>

<%#= link_to 'Films', films_path %>

app/views/reviews/show.html.erb
<h2>Review for <%= @review.film.title %></h2>



<p><%= @review.comment %></p>
<p><%= @review.author %></p>

<%#= link_to 'Films', films_path %>

<%= link_to @review.film.title, film_path(@review.film) %>


<%= link_to 'Edit Review', edit_review_path(@review) %>

<%= button_to 'Delete Review', review_path(@review),
                  method: :delete, data: { confirm: 'Are you sure?' } %>